apiVersion: platform.refplat.org/v1beta1
kind: XEnvironment
metadata:
  name: alpha-conformance-dev
  annotations:
    platform.refplat.org/requested-by: user:default/dev-alpha
spec:
  team: alpha
  product: conformance
  stage: dev
  tier: standard
  services:
    web:
      serviceAccount: app-alpha
      resources:
        blob:
          kind: objectstore
          engine: s3
          access: readwrite
        jobs:
          kind: stream
          engine: sqs
          access: readwrite
        events:
          kind: stream
          engine: sns
          access: readwrite
        sessions:
          kind: keyvalue
          engine: dynamodb
          access: readwrite
