apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: platform-flagship-dev
spec:
  environmentRef: platform-flagship-dev
  services:
    server:
      digest: sha256:992130b68eaf260c5c0881cce17e35c093fbc87abb12e2c97b629a0a651c9d8a
