apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: platform-flagship-dev
spec:
  environmentRef: platform-flagship-dev
  services:
    server:
      digest: sha256:06af87cd260448ff2f18c130638ea6007de0c92d6ccdbe79f3fcd84391181715
