/**
 * Provider requirements for the AKS Identity module
 * 
 * NOTE: THIS FILE IS DOCUMENTATION ONLY - NOT USED IN ACTUAL CONFIGURATION
 * The actual provider configuration is generated by Terragrunt.
 *
 * Required providers:
 * - azurerm: Used to interact with Azure resources
 */

/*
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.23.0"
    }
  }
}

provider "azurerm" {
  features {}
}
*/ 