package validate

// goldenResolveCheckers is the pinned, sorted signature of every check ResolveCheckers produces for the
// comprehensive unit set in resolvecheckers_golden_test.go. Captured from the pre-registry-refactor switch;
// the switch→registry conversion must reproduce it exactly.
var goldenResolveCheckers = []string{
	"platform/argocd-apps/state -> *validate.StateCheck",
	"platform/argocd-clusters/state -> *validate.StateCheck",
	"platform/argocd/apps -> *validate.ArgoCDAppCheck",
	"platform/argocd/pods -> *validate.K8sWorkloadCheck",
	"platform/argocd/state -> *validate.StateCheck",
	"platform/cert-manager/pods -> *validate.K8sWorkloadCheck",
	"platform/cert-manager/state -> *validate.StateCheck",
	"platform/cilium/pods -> *validate.K8sWorkloadCheck",
	"platform/cilium/state -> *validate.StateCheck",
	"platform/cloudtrail/state -> *validate.StateCheck",
	"platform/cross-vpc-dns/dns/preprod -> *validate.CrossVPCDNSCheck",
	"platform/cross-vpc-dns/state -> *validate.StateCheck",
	"platform/crossplane/state -> *validate.StateCheck",
	"platform/ecr/state -> *validate.StateCheck",
	"platform/eks-addons/coredns -> *validate.K8sWorkloadCheck",
	"platform/eks-addons/state -> *validate.StateCheck",
	"platform/eks/cluster -> *validate.EKSClusterCheck",
	"platform/eks/state -> *validate.StateCheck",
	"platform/external-dns/pods -> *validate.K8sWorkloadCheck",
	"platform/external-dns/state -> *validate.StateCheck",
	"platform/external-secrets/pods -> *validate.K8sWorkloadCheck",
	"platform/external-secrets/state -> *validate.StateCheck",
	"platform/gateway-config/state -> *validate.StateCheck",
	"platform/github-oidc/state -> *validate.StateCheck",
	"platform/iam-roles/state -> *validate.StateCheck",
	"platform/karpenter/ready -> *validate.KarpenterReadyCheck",
	"platform/karpenter/state -> *validate.StateCheck",
	"platform/mystery/state -> *validate.StateCheck",
	"platform/networking/state -> *validate.StateCheck",
	"platform/node-groups/state -> *validate.StateCheck",
	"platform/policy/admission -> *validate.AdmissionBlockedCheck",
	"platform/policy/state -> *validate.StateCheck",
	"platform/route53-delegation/state -> *validate.StateCheck",
	"platform/route53/state -> *validate.StateCheck",
	"platform/secret-stores/state -> *validate.StateCheck",
	"platform/secret-stores/status -> *validate.SecretStoreCheck",
	"platform/ssm-bastion/state -> *validate.StateCheck",
	"platform/tailscale-admin/state -> *validate.StateCheck",
	"platform/tailscale/operator -> *validate.K8sWorkloadCheck",
	"platform/tailscale/state -> *validate.StateCheck",
	"platform/transit-gateway/attachments -> *validate.TGWAttachmentCheck",
	"platform/transit-gateway/state -> *validate.StateCheck",
}
