apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-conformance-dev
spec:
  environmentRef: alpha-conformance-dev
  services:
    web:
      digest: sha256:89a0b5c109194db7cec33f3eb4a65cd9e54579aea8d2d7a0e300fcef492e0084
