apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-conformance-dev
spec:
  environmentRef: alpha-conformance-dev
  services:
    web:
      digest: sha256:3956655b87b228a11595dffc47975c1fb50dab440a3fee612925213a90245acc
