apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-conformance-dev
spec:
  environmentRef: alpha-conformance-dev
  services:
    web:
      digest: sha256:1ec6b9db7daf88ffc7269b7438888806741cd995e9a3d55fd1bded3a7f2f3cef
