apiVersion: platform.refplat.org/v1beta1
kind: XEnvironment
metadata:
  name: alpha-checkout-test
  annotations:
    platform.refplat.org/requested-by: user:default/dev-alpha
    platform.refplat.org/decommissioned-at: 2026-06-16T17:49:27.017Z
spec:
  team: alpha
  product: checkout
  stage: test
  tier: standard
  services:
    web:
      serviceAccount: app-alpha
      preview: false
  lifecycle:
    phase: decommissioning
