apiVersion: platform.refplat.org/v1beta1
kind: XEnvironment
metadata:
  name: alpha-payments-dev
  annotations:
    platform.refplat.org/requested-by: user:default/dev-alpha
    platform.refplat.org/decommissioned-at: 2026-06-16T19:21:59.491Z
spec:
  team: alpha
  product: payments
  stage: dev
  tier: standard
  services:
    web:
      serviceAccount: app-alpha
  lifecycle:
    phase: decommissioning
