apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-shop-dev
spec:
  environmentRef: alpha-shop-dev
  services:
    web:
      digest: sha256:968cdb5b7ef350764abdf179224cb44cb656a4cb73fcc7ed00efdd87a8c6606f
