apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-shop-prod
spec:
  environmentRef: alpha-shop-prod
  services:
    web:
      digest: sha256:1ca54af982e1ebfb5c51dbd94adaadadd055819f0ad29f640e14965bd580d3a8
