apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-shop-prod
spec:
  environmentRef: alpha-shop-prod
  services:
    web:
      digest: sha256:f6b37d869df95615498ba621fd8f897ad09b8fcdf94082b59abef9523f2117ec
