apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-shop-test
spec:
  environmentRef: alpha-shop-test
  services:
    orders:
      digest: sha256:acfd5d0a76cc6b70bc2f21c4aae94e5afeb0d0e6deba8181ec1aadf00504e5ce
