apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-checkout-dev
spec:
  environmentRef: alpha-checkout-dev
  services:
    web:
      digest: sha256:724ada40e8832089dfb5c83e91ea1075155e307ac60daac7ce533e659cac42de
