apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-checkout-dev
spec:
  environmentRef: alpha-checkout-dev
  services:
    web:
      digest: sha256:368c1ea37b2845238a5c9011d4839af4e58cc591116115ac810eff446c8d2175
