apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: alpha-checkout-dev
spec:
  environmentRef: alpha-checkout-dev
  services:
    web:
      digest: sha256:b4aa5a3b16dbb8c8babc75c8283e19b48417fcb3e1583fda71324d10cd640a32
