apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: bravo-dispatch-test
spec:
  environmentRef: bravo-dispatch-test
  services:
    dispatch-worker:
      digest: sha256:fa263c8b04db7b5f883184a74817ea7be0d525d9e973a5c6d7804c352849df95
