/**
 * Provider requirements for the Azure Storage Account module
 * 
 * NOTE: THIS FILE IS DOCUMENTATION ONLY - NOT USED IN ACTUAL CONFIGURATION
 * The actual provider configuration is generated by Terragrunt.
 *
 * Required providers:
 * - azurerm: Used to interact with Azure resources
 */

/*
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.25.0"
    }
  }
  required_version = ">= 1.0.0"
}
*/ 