/*
This file is for documentation purposes only.
The actual provider configuration comes from Terragrunt generation.

Required Providers:
- azurerm: Provider for Azure resources (version = "4.23.0")
*/

# Terraform required providers are specified in the Terragrunt configuration.
# This empty block is left here for documentation purposes only.
terraform {
  # Terragrunt generates the actual required_providers block
}

# The actual provider configuration is generated by Terragrunt
# Provider configuration parameters:
# - features: {}
# - subscription_id: From environment variable or Terragrunt config
# - use_cli: true (uses Azure CLI authentication) 