apiVersion: platform.refplat.org/v1beta1
kind: XEnvironment
metadata:
  name: alpha-shop-dev
  annotations:
    platform.refplat.org/requested-by: user:default/dev-alpha
    platform.refplat.org/decommissioned-at: 2026-06-16T15:36:56.635Z
spec:
  team: alpha
  product: shop
  stage: dev
  tier: standard
  services:
    web:
      serviceAccount: app-alpha
  lifecycle:
    phase: decommissioning
