apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: platform-triage-copilot-dev
spec:
  environmentRef: platform-triage-copilot-dev
  services:
    server:
      digest: sha256:66f4a5de0e3ce5930ebe47979c8d28224bb163073368d2342f94c20226c7607e
