apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: platform-triage-copilot-dev
spec:
  environmentRef: platform-triage-copilot-dev
  services:
    server:
      digest: sha256:846d4f63f4f0a70c87f27e771f783b115902bbbf605064c0275294cdfe36da98
