apiVersion: platform.refplat.org/v1beta1
kind: Release
metadata:
  name: platform-triage-copilot-dev
spec:
  environmentRef: platform-triage-copilot-dev
  services:
    server:
      digest: sha256:44185189d40c33b76a5e8338d25312ff28136d136d149f3a264af051fb5c2503
