include "base" {
  path   = find_in_parent_folders("aws/_base.hcl")
  expose = true
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = include.base.locals.module_source.dns_delegation
}

dependency "route53" {
  config_path = "../route53"

  mock_outputs = {
    name_servers = ["ns-1.awsdns-01.com", "ns-2.awsdns-02.net", "ns-3.awsdns-03.org", "ns-4.awsdns-04.co.uk"]
  }
  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan", "destroy"]
}

generate "versions_override" {
  path = "versions.tf"
  # overwrite (not overwrite_terragrunt): the sourced dns_delegation module ships its own committed versions.tf
  # (ADR-083), which overwrite_terragrunt refuses to touch ("already exists and was not generated by terragrunt").
  # This unit needs the aws provider too (root.hcl generates provider_aws.tf + the route53 dependency), so it
  # replaces the module's cloudflare-only versions.tf outright. Matches the tailscale-admin pattern.
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  required_version = ">= 1.6.0"
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}
EOF
}

generate "provider_cloudflare" {
  path      = "provider_cloudflare.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
data "aws_secretsmanager_secret_version" "cloudflare_token" {
  secret_id = "platform/cloudflare/api-token"
}

provider "cloudflare" {
  api_token = data.aws_secretsmanager_secret_version.cloudflare_token.secret_string
}
EOF
}

inputs = {
  create             = true
  cloudflare_zone_id = include.base.locals.all_vars.cloudflare_zone_id
  subdomain          = "aws"
  nameservers        = dependency.route53.outputs.name_servers
}
