include "base" {
  path   = find_in_parent_folders("aws/_base.hcl")
  expose = true
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = include.base.locals.module_source.pagerduty
}

# Teams to provision on-call structure for — derived from the canonical Team registry (gitops/teams/,
# ADR-063), the same YAMLs ArgoCD syncs to the cluster. We need only the names here (one schedule / EP /
# service per team), so the map value is a fixed empty shape — a Team-spec field some teams have and
# others don't can't make the element types inconsistent (same pattern as keycloak-config).
locals {
  teams_dir = "${get_repo_root()}/gitops/teams"
  teams = { for f in fileset(local.teams_dir, "*.yaml") :
    yamldecode(file("${local.teams_dir}/${f}")).metadata.name => {}
  }
}

generate "versions_override" {
  path = "versions.tf"
  # "overwrite" (not "overwrite_terragrunt"): the module ships its own versions.tf, which terragrunt refuses to
  # overwrite under "overwrite_terragrunt" ("file already exists and was not generated by terragrunt"). This bites
  # the cloudflare-dns reference unit too (a latent bug) — fixed here.
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  required_version = ">= 1.6.0"
  required_providers {
    pagerduty = {
      source  = "PagerDuty/pagerduty"
      version = "~> 3.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}
EOF
}

# PagerDuty provider — token from the PAGERDUTY_TOKEN env var, injected by platctl via
# `env_from_secret` (.platctl.yaml) from Secrets Manager platform/pagerduty/api-token (created by
# hand). It is DELIBERATELY not read via a Terraform data source in the provider block: a data
# source referenced from a provider config evaluates empty during `terraform destroy`, so the
# provider can't authenticate to tear down its own PagerDuty resources ("No valid credentials
# found"). Env-sourcing sidesteps that. NB a MANUAL `terragrunt apply/destroy` of this unit must
# export PAGERDUTY_TOKEN first (platctl does it automatically). The aws provider comes from
# root.hcl (PlatformDeployer). Cloud-only unit (no cluster dependency).
generate "provider_pagerduty" {
  path      = "provider_pagerduty.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "pagerduty" {}
EOF
}

inputs = {
  teams = local.teams

  # Existing PagerDuty admin — referenced, never created (ADR-084). Seeds every schedule until the
  # directory-derived membership connector lands (the bootstrap seam, see the module).
  bootstrap_oncall_email = "pagerduty@hatermail.com"

  tags = include.base.locals.tags
}
