apiVersion: platform.refplat.org/v1alpha2
kind: XTenant
metadata:
  name: charlie-web-dev
  annotations:
    platform.refplat.org/requested-by: user:default/admin
    platform.refplat.org/decommissioned-at: 2026-06-10T05:48:15.982Z
spec:
  team: charlie
  name: web
  environment: dev
  apps:
    web:
      repo: asanexample/app-charlie
      preview: false
      serviceAccount: app-charlie
  developerAccess:
    enabled: true
  lifecycle:
    phase: decommissioning
